app:
  name: "Logging"
  display_name: "日志示例"
  description: "演示MOD框架的多种日志输出功能"
  version: "1.0.0"
  service_base: "/services"

server:
  host: "localhost"
  port: 8080
  cors:
    enabled: true
    allow_origins: ["*"]
    allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allow_headers: ["Origin", "Content-Type", "Accept", "Authorization"]

# 日志配置 - 支持多种输出方式
logging:
  # 控制台日志
  console:
    enabled: true
    level: "debug"  # debug, info, warn, error

  # 文件日志 - 支持日志轮转
  file:
    enabled: true
    path: "./logs/app.log"
    max_size: "100MB"     # 单个日志文件最大大小
    max_backups: 10       # 保留的历史日志文件数量
    max_age: "30d"        # 日志文件保留时间
    compress: true        # 是否压缩历史日志文件

  # Grafana Loki 日志聚合（示例配置，需要实际Loki服务）
  loki:
    enabled: false
    url: "http://localhost:3100/loki/api/v1/push"
    labels:
      service: "mod-logging-example"
      environment: "development"
    batch_size: 100
    timeout: "10s"

  # 阿里云SLS日志服务（示例配置，需要实际凭证）
  sls:
    enabled: false
    endpoint: "cn-shenzhen.log.aliyuncs.com"
    project: "my-project"
    logstore: "my-logstore"
    access_key_id: "your-access-key-id"
    access_key_secret: "your-access-key-secret"